Issue #SB-13991 feat: added update available when content is updated
Sunbird-Ed/openrap-sunbirded-plugin pull request #38
Opened 2019-09-25 08:20 UTC by swetha-aggidevara

2019-09-30 08:56 UTC, HarishGangula requested changes
@swetha-aggidevara resolve all the review comments and let me know

2019-09-30 08:56 UTC, harishgilimi commented on server/controllers/content/content.ts
> +export enum CONTENT_UPDATE {
This is wrong,  check the name of the enum and what it contains
and everything should be consistent in enum https://www.typescriptlang.org/docs/handbook/enums.html
which follows standard all the values should be in uppercase
Why this is required ?

2019-09-30 08:56 UTC, harishgilimi commented on server/controllers/content/content.ts
> +                    resolve(offlineContent);
Why we are not logging error here?

2019-09-30 08:56 UTC, harishgilimi commented on server/routes.spec.ts
> +                if (err && res.stausCode >= 400) { expect.fail(); return done(); };
spelling mistake here **statusCode**

2019-09-30 09:00 UTC, swetha-aggidevara commented on server/controllers/content/content.ts
> +                    resolve(offlineContent);
If there is no Internet we need to send same data

2019-09-30 09:22 UTC, harishgilimi commented on server/controllers/content/content.ts
> +                    resolve(offlineContent);
Yes, but how I will know what is the error in logs if I want to debug?

2019-10-01 06:07 UTC, HarishGangula approved these changes

2019-10-01 06:07 UTC, merged