Issue #SB-14332 feat: export content refactor to sync file structure with content import and mobile app
Sunbird-Ed/openrap-sunbirded-plugin pull request #50
Opened 2019-11-05 10:44 UTC by anoophm

2019-11-05 12:56 UTC, HarishGangula requested changes

2019-11-05 12:56 UTC, harishgilimi commented on server/controllers/content/content.ts
>                  res.status(500);
Log the  error

2019-11-05 12:56 UTC, harishgilimi commented on server/controllers/content/content.ts
> +            console.log('Ecar exported successfully', data);
remove console logs

2019-11-05 12:56 UTC, harishgilimi commented on server/manager/contentExportManager/contentExport.ts
> +      this.parentManifest = await fse.readJson(this.join(this.contentBaseFolder, this.dbParentDetails.identifier,  'manifest.json'));
use fileSDK

2019-11-05 12:56 UTC, harishgilimi commented on server/manager/contentExportManager/contentExport.ts
> +    this.parentArchive = archiver('zip', { zlib: { level: 9 }});
move to fileSDK

2019-11-05 12:56 UTC, harishgilimi commented on server/manager/contentExportManager/contentExport.ts
> +
Write comments to each method

2019-11-05 15:32 UTC, anoophm commented on server/controllers/content/content.ts
>                  res.status(500);
contentExport.export has error log

2019-11-06 04:15 UTC, HarishGangula approved these changes

2019-11-06 04:15 UTC, merged