Issue #SB-15375 feat: User add and read api
Sunbird-Ed/openrap-sunbirded-plugin pull request #64
Opened 2019-11-15 12:34 UTC by souravdey091

2019-11-18 10:17 UTC, HarishGangula requested changes

2019-11-18 10:17 UTC, harishgilimi commented on server/controllers/user.ts
> +    async addUser(req, res) {
The methodname should be create

2019-11-18 10:17 UTC, harishgilimi commented on server/controllers/user.ts
> +    async getUser(req, res) {
This method name should be read

2019-11-18 10:17 UTC, harishgilimi commented on server/controllers/user.ts
> +            return res.send(Response.success('api.desktop.user.read', userData, req));
Should  handle 404 cases separately

2019-11-18 10:17 UTC, harishgilimi commented on server/routes.ts
> +    app.post("/api/desktop/user/v1/create", (req, res) => {
This can be user.addUser.bind(user)

2019-11-18 10:17 UTC, harishgilimi commented on server/routes.ts
> +    app.get("/api/desktop/user/v1/read", (req, res) => {
user.getUser.bind(user)

2019-11-19 12:28 UTC, HarishGangula requested changes

2019-11-19 12:28 UTC, harishgilimi commented on server/controllers/user.ts
> +            const createResp = await this.userSDK.create(_.get(req, 'body.request'));
validation required for the request body

2019-11-19 12:28 UTC, harishgilimi commented on server/controllers/user.ts
> +            logger.error(`ReqId = "${req.headers['X-msgid']}": Received error while getting user,  where err = ${err}`);
res.status() and res.send status should be same

2019-11-19 17:14 UTC, HarishGangula approved these changes

2019-11-19 17:14 UTC, merged