Issue #SB-16355 feat: added app info endpoint
Sunbird-Ed/openrap-sunbirded-plugin pull request #84
Opened 2019-12-16 10:31 UTC by swetha-aggidevara

2019-12-16 11:34 UTC, anoophm approved these changes

2019-12-17 05:34 UTC, HarishGangula requested changes

2019-12-17 05:34 UTC, harishgilimi commented on server/controllers/appUpdate.ts
> +    public getAppInfo(req, res) {
All the required info need to be sent from api

2019-12-17 05:34 UTC, harishgilimi commented on server/controllers/appUpdate.ts
> +                languages: config.get("LANGUAGES").split(","),
No need to split the Languages

2019-12-17 10:16 UTC, HarishGangula approved these changes

2019-12-17 10:17 UTC, merged